- hosts: video
  become: yes
  vars_prompt:
    - name: minio_access_key
      prompt: login
      default: rooty
      private: no

    - name: minio_secret_key
      prompt: password
      default: evangelina
      private: yes

    - name: holly_version
      prompt: holly version
      default: latest
      private: no

  tasks:
    - name: create nginx dirs
      file: path=/data/nginx/config state=directory recurse=yes

    - name: copy nginx config
      template: src=site.conf dest=/data/nginx/config

    - name: start proxy
      docker_container:
        name: nginx
        image: nginx
        volumes:
          - /data/nginx/config:/etc/nginx/conf.d
        ports:
          - '80:80'


    - name: create minio dirs
      file: path=/data/minio/export state=directory recurse=yes

    - name: start minio
      docker_container:
        name: minio
        image: minio/minio
        volumes:
          - /data/minio/export:/export
        command: /export
        ports:
          - '9000:9000'
        env:
          MINIO_ACCESS_KEY: "{{ minio_access_key }}"
          MINIO_SECRET_KEY: "{{ minio_secret_key }}"


    - name: start holly
      docker_container:
        name: holly
        image: "0x06065a/holly-node:{{ holly_version }}"
        ports:
          - '3000:3000'
        links:
          - minio:minio
        env:
          MINIO_HOST: "{{ ansible_default_ipv4.address }}"
          MINIO_PORT: 9000
          MINIO_URL: "{{ ansible_default_ipv4.address }}/minio"
          MINIO_ACCESS_KEY: "{{ minio_access_key }}"
          MINIO_SECRET_KEY: "{{ minio_secret_key }}"
