- hosts: video
  become: yes
  vars_prompt:
    - name: holly_version
      prompt: holly version
      default: latest
      private: no

    - name: videos_dir
      prompt: videos directory
      default: /data/holly 
      private: no
  tasks:
    - name: create nginx dirs
      file: path=/data/nginx/config state=directory recurse=yes

    - name: copy nginx config
      template: src=site.conf dest=/data/nginx/config

    - name: create data dirs
      file: path=/data/holly state=directory recurse=yes


    - name: start proxy
      docker_container:
        name: nginx
        image: nginx
        volumes:
          - /data/nginx/config:/etc/nginx/conf.d
          - "{{ videos_dir }}:/data/holly"
        ports:
          - '80:80'


    - name: start holly
      docker_container:
        name: holly
        image: "0x06065a/holly-node:{{ holly_version }}"
        volumes:
          - "{{ videos_dir }}:/data/holly"
        ports:
          - '3000:3000'
        env:
          VIDEOS_DIR: /data/holly
          VIDEOS_SERVER_URL: "http://{{ ansible_default_ipv4.address }}/storage"
